# https://travis-ci.org/pytorch/pytorch
language: python
dist: trusty
git:
  submodules: false

# This reportedly works around an issue downloading packages from pypi on
# travis.  Consider removing this after the underlying issue is fixed.
# https://github.com/travis-ci/travis-ci/issues/2389
sudo: false

matrix:
    fast_finish: true
    include:
      - env: LINT_CHECK
        python: "2.7"
        install: pip install flake8
        script: flake8
      - env: LINT_CHECK
        python: "3.7"
        dist: xenial    # required for Python 3.7 (travis-ci/travis-ci#9069)
        sudo: required  # required for Python 3.7 (travis-ci/travis-ci#9069)
        install: pip install flake8
        script: flake8
      - env: MYPY_TYPE_CHECK
        python: "3.6"
        install: pip install mypy mypy-extensions
        script: mypy @mypy-files.txt
      - env: CPP_DOC_CHECK
        install: sudo apt-get install -y doxygen
        script: cd docs/cpp/source && ./check-doxygen.sh
      - env: CLANG_TIDY
        python: "3.6"
        addons:
          apt:
            sources:
              - ubuntu-toolchain-r-test
              - llvm-toolchain-trusty-6.0
            packages: clang-tidy-6.0
        script: tools/run-clang-tidy-in-ci.sh -e "$(which clang-tidy-6.0)"

install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION pytorch scipy -c pytorch
  - source activate test-environment

script:
  - python train.py

