PCB: false
batchsize: 32
color_jitter: false
data_dir: ../Market/pytorch
droprate: 0.5
erasing_p: 0.5
fp16: false
gpu_ids: '0'
lr: 0.05
name: warm5_s1_p0.5
nclasses: 751
stride: 1
train_all: false
use_NAS: false
use_dense: false
warm_epoch: 5
